
image-caprover-image: &image-caprover-image
  platform: linux
  image_resource:
    type: docker-image
    source:
      repository: srv-captain--docker-registry:5000/darkspirit510/caprover-image
      tag: latest
      insecure_registries:
        - "srv-captain--docker-registry:5000"

jobs:
  - name: deploy-reporter
    serial: true
    plan:
      - get: source-code
        trigger: true
      - task: deploy
        params:
          CAPROVER_URL: ((caprover_url))
          CAPROVER_PASSWORD: ((caprover_password))
          CAPROVER_APP: ((caprover_appname))
        config:
          <<: *image-caprover-image
          inputs:
            - name: docker-source
          run:
            path: bash
            args:
              - -ecux
              - |
                cd source-code/
                ./gradlew jar

                cp build/libs/overviewer-reporter.jar .

                tar -cf overviewer-reporter.jar./overviewer-reporter.tar source-code/Dockerfile source-code/captain-definition
                caprover deploy -t ./overviewer-reporter.tar

resources:
  - name: source-code
    type: git
    icon: github-circle
    source:
      uri: https://github.com/darkspirit510/overviewer-reporter.git
