
image-caprover-image: &image-caprover-image
  platform: linux
  image_resource:
    type: docker-image
    source:
      repository: srv-captain--docker-registry:5000/darkspirit510/caprover-image
      tag: latest
      insecure_registries:
        - "srv-captain--docker-registry:5000"

image-openjdk-8: &image-openjdk-8
  platform: linux
  image_resource:
    type: docker-image
    source:
      repository: openjdk
      tag: 8

jobs:
  - name: deploy-reporter
    serial: true
    plan:
      - get: source-code
        trigger: true
      - task: build
        config:
          <<: *image-openjdk-8
          inputs:
            - name: source-code
          outputs:
            - name: reporter
          run:
            path: bash
            args:
              - -ecu
              - |
                PWD=$(pwd)
                cd source-code/
                ./gradlew jar --no-daemon
                cp build/libs/overviewer-reporter.jar $PWD/artifacts

      - task: deploy
        params:
          CAPROVER_URL: ((caprover_url))
          CAPROVER_PASSWORD: ((caprover_password))
          CAPROVER_APP: ((caprover_appname))
        config:
          <<: *image-caprover-image
          inputs:
            - name: source-code
            - name: artifacts
          run:
            path: bash
            args:
              - -ecu
              - |
                cp artifacts/overviewer-reporter.jar source-code/
                cd source-code/

                tar -cf overviewer-reporter.jar./overviewer-reporter.tar source-code/Dockerfile source-code/captain-definition
                caprover deploy -t ./overviewer-reporter.tar

resources:
  - name: source-code
    type: git
    icon: github-circle
    source:
      uri: https://github.com/darkspirit510/overviewer-reporter.git
